version: '3'

# The .env file is for production use with server-specific configurations

services:
  postgres:
    restart: always
    image: pennprov/hab-postgres:v1
    environment:
     - POSTGRES_USER:postgres
     - POSTGRES_PASSWORD:'habitat1'
     - POSTGRES_DB:'habitat'
    ports:
     - '5432:5432'

  neo4j:
    restart: always
    image: neo4j:3.5
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
     NEO4J_AUTH: "neo4j/habitat1"

  penn-provenance:
    restart: always
    image: pennprov/penn-provenance:v2.3
    ports:
     - '8088:8088'
    depends_on:
     - postgres
     - neo4j