version: '3'

services:
# Frontend web proxy for accessing services and providing TLS encryption
  nginx:
    build:
      context: ./nginx
    container_name: cerebralcortex-nginx
    restart: always
    volumes:
      - ./nginx/site:/var/www
      - ./nginx/nginx-selfsigned.crt:/etc/ssh/certs/ssl-cert.crt
      - ./nginx/nginx-selfsigned.key:/etc/ssh/certs/ssl-cert.key
      - ./nginx/insecure_site.conf:/etc/nginx/site.conf
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - grafana
      - apiserver
      - jupyter

  apiserver:
    image: md2korg/cerebralcortex-apiserver:3.3.2
    container_name: cerebralcortex-apiserver
    restart: always
    expose:
      - 80
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=${MYSQL:-mysql}
      - MYSQL_DB_USER=${MYSQL_ROOT_USER:-root}
      - MYSQL_DB_PASS=${MYSQL_ROOT_PASSWORD:-pass}
    volumes:
      - ./mount_points/apiserver/data:/data
      - ./mount_points/apiserver:/cc_bucket
      - ./cc_conf:/cc_conf

# Data vizualizations
  grafana:
    image: grafana/grafana
    container_name: cerebralcortex-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    user: "0"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
    volumes:
      - ./mount_points/grafana/data:/var/lib/grafana
      - ./mount_points/grafana/logs:/var/log/grafana
      - ./grafana:/etc/grafana/provisioning

  influxdb:
    image: influxdb:alpine
    container_name: cerebralcortex-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./mount_points/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB="cerebralcortex_raw"

# Data Science Dashboard Interface
  jupyter:
    image: md2korg/cerebralcortex-jupyter:3.3.2
    #build: ../CerebralCortex-Jupyter
    container_name: cerebralcortex-jupyterhub
    ports:
      - 8000
    restart: always
    environment:
      - NB_USER=jovyan
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
      - GRANT_SUDO="yes"
    user: root
    volumes:
      - ./cc_conf:/home/jovyan/cc_conf
      - ./jupyter/conf:/etc/jupyter/
      - ./mount_points/apiserver/data:/data
      - ./mount_points/apiserver:/cc_bucket
      - ./jupyter_demo:/home/jovyan/jupyter_demo
    # command: sh -c "chown -R md2k /data/ && jupyterhub --no-ssl --config /srv/jupyterhub/conf/jupyterhub_config.py"

  mysql:
    image: mysql:5.7
    container_name: cerebralcortex-mysql
    restart: always
    labels:
        org.md2k.cerebralcortex.name: "MySql"
    ports:
      - 3306:3306 # Default mysql port
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-pass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cerebralcortex}
      - MYSQL_USER=${MYSQL_USER:-cerebralcortex}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-cerebralcortex_pass}
    volumes:
      #- ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mount_points/mysql:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/mysql.cnf
