{
 "title": "MD2K",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Smartphone Motion Sensors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Accel-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACCELEROMETER--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Accelerometer-X" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "X" ], "type": "alias" }
      ],
      [
       { "params": [ "Accelerometer-Y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Y" ], "type": "alias" }
      ],
      [
       { "params": [ "Accelerometer-Z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Z" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Gyro-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GYROSCOPE--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Gyroscope-X" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "X" ], "type": "alias" }
      ],
      [
       { "params": [ "Gyroscope-Y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Y" ], "type": "alias" }
      ],
      [
       { "params": [ "Gyroscope-Z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Z" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Mag-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "COMPASS--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Compass-X" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "X" ], "type": "alias" }
      ],
      [
       { "params": [ "Compass-Y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Y" ], "type": "alias" }
      ],
      [
       { "params": [ "Compass-Z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Z" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity Classifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACTIVITY_TYPE--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Confidence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ACTIVITY_TYPE--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "value_1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smartphone Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LOCATION--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Altitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Altitude" ], "type": "alias" }
      ],
      [
       { "params": [ "Accuracy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Accuracy" ], "type": "alias" }
      ],
      [
       { "params": [ "Speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Smartphone",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BATTERY--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MotionSense (Left)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BATTERY--org.md2k.motionsense--MOTION_SENSE_HRV_PLUS--LEFT_WRIST",
     "select": [
      [
       { "params": [ "Battery-Level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MotionSense (Right)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BATTERY--org.md2k.motionsense--MOTION_SENSE_HRV_PLUS--RIGHT_WRIST",
     "select": [
      [
       { "params": [ "Battery-Level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Step Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Smartphone",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "STEP_COUNT--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "Step-Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smartphone Touch Screen Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Touches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "TOUCH_SCREEN--org.md2k.mcerebrum--PHONE",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MotionSense Data Yield (Motion)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MotionSense (Left)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV_PLUS--LEFT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "MotionSense (Right)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV_PLUS--RIGHT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Stream Samples",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "logBase": 1,
     "query": "SELECT count(*) FROM /.*/ WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}